name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build image
        run: docker build -t agentforge:ci .
      - name: SBOM (CycloneDX)
        run: |
          pip install cyclonedx-bom
          cyclonedx-py --format json --outfile sbom.json
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: agentforge:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
      - name: Cosign install
        uses: sigstore/cosign-installer@v3.5.0
      - name: Cosign sign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign --yes --predicate sbom.json --recursive agentforge:ci

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up kind + kubectl + kustomize
        uses: helm/kind-action@v1.10.0
      - name: Load image into kind
        run: kind load docker-image agentforge:ci
      - name: Deploy staging
        run: |
          kubectl apply -k k8s/staging
          kubectl rollout status deploy/nats -n agentforge-staging --timeout=120s
          kubectl rollout status deploy/temporalite -n agentforge-staging --timeout=120s
          kubectl rollout status deploy/nats-worker -n agentforge-staging --timeout=180s || true
          kubectl rollout status deploy/temporal-worker -n agentforge-staging --timeout=180s || true
      - name: Seed JetStream and smoke publish
        run: |
          python -m pip install nats-py
          python scripts/nats_setup.py
          python scripts/smoke_publish.py
      - name: Check worker logs
        run: |
          kubectl logs deploy/nats-worker -n agentforge-staging --tail=200 || true
          kubectl logs deploy/temporal-worker -n agentforge-staging --tail=200 || true
