apiVersion: v1
kind: Namespace
metadata:
  labels:
    airgap: "true"
    app.kubernetes.io/part-of: agentforge
  name: agentforge-scif
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentforge
  namespace: agentforge-scif
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agentforge-basic
  namespace: agentforge-scif
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentforge-binding
  namespace: agentforge-scif
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agentforge-basic
subjects:
- kind: ServiceAccount
  name: agentforge
  namespace: agentforge-scif
---
apiVersion: v1
data:
  AIRGAPPED: "1"
  CRITIC_HEALER_ENABLED: "1"
  DISPATCH_MODE: nats
  ENV: scif
  EXTERNAL_TOOLS: "0"
  LOCAL_ARTIFACTS_DIR: /app/var/artifacts
  MEMORY_MESH_MODE: dist
  MISSION: scif
  NATS_FETCH_BATCH: "4"
  NATS_FETCH_WAIT: "8.0"
  NATS_URL: nats://nats:4222
  SECURITY_HARDENED: "1"
  SLA_MAX_CALIB_ERROR: "1.0"
  SLA_MAX_ERROR_RATE: "0.0"
  SLA_MAX_UNCERTAINTY: "1.0"
  SLA_MIN_COMPLETENESS: "0.8"
  SWARM_DB_URL: sqlite:////app/var/swarm.db
  TEMPORAL_ADDRESS: temporal.prod.scif.local:7233
  TEMPORAL_NAMESPACE: default
  TEMPORAL_TASK_QUEUE: agentforge
  VECTOR_DB_URL: sqlite:////app/var/vector.db
  VECTOR_ENABLED: "1"
  VECTOR_SYNC: "0"
kind: ConfigMap
metadata:
  name: agentforge-config
  namespace: agentforge-scif
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: agentforge-secrets
  namespace: agentforge-scif
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: agentforge-scif
spec:
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitoring
    port: 8222
    targetPort: 8222
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: agentforge-scif
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pgvector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - args:
        - -js
        - -m
        - "8222"
        - -sd
        - /data/jetstream
        image: registry.local/nats:2.10-alpine@sha256:1111111111111111111111111111111111111111111111111111111111111111
        name: nats
        ports:
        - containerPort: 4222
        - containerPort: 8222
        volumeMounts:
        - mountPath: /data
          name: nats-data
      terminationGracePeriodSeconds: 15
      volumes:
      - emptyDir: {}
        name: nats-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-worker
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-worker
  template:
    metadata:
      labels:
        app: nats-worker
    spec:
      containers:
      - command:
        - python
        - -m
        - swarm.workers.nats_worker
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        envFrom:
        - configMapRef:
            name: agentforge-config
        image: registry.local/agentforge:latest@sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        name: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - command:
        - python
        - -m
        - uvicorn
        - services.orchestrator.app.main:app
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: agentforge-config
        image: registry.local/agentforge:latest@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        imagePullPolicy: IfNotPresent
        name: orchestrator
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: example
        image: registry.local/ankane/pgvector:latest@sha256:2222222222222222222222222222222222222222222222222222222222222222
        name: pgvector
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-sink
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-sink
  template:
    metadata:
      labels:
        app: results-sink
    spec:
      containers:
      - command:
        - python
        - -m
        - swarm.workers.results_sink_worker
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: agentforge-config
        image: registry.local/agentforge:latest@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        name: sink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-executor
  namespace: agentforge-scif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool-executor
  template:
    metadata:
      labels:
        app: tool-executor
    spec:
      containers:
      - command:
        - python
        - -m
        - swarm.workers.tool_executor_worker
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: agentforge-config
        image: registry.local/agentforge:latest@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        imagePullPolicy: IfNotPresent
        name: tool-executor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agentforge-services
  namespace: agentforge-scif
spec:
  endpoints:
  - interval: 30s
    port: monitoring
  namespaceSelector:
    matchNames:
    - agentforge-scif
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nats
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: agentforge-scif
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-only
  namespace: agentforge-scif
spec:
  egress:
  - to:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: agentforge-scif
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
