name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'
      - name: Build image
        run: docker build -t agentforge:ci .
      - name: SBOM (CycloneDX)
        run: |
          pip install cyclonedx-bom
          cyclonedx-py --format json --outfile sbom.json
      - name: Trivy scan
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        with:
          image-ref: agentforge:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
      - name: Cosign install
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
      - name: Cosign sign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign --yes --predicate sbom.json --recursive agentforge:ci

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up kind + kubectl + kustomize
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde
      - name: Load image into kind
        run: kind load docker-image agentforge:ci
      - name: Deploy staging
        run: |
          kubectl apply -k k8s/staging
          kubectl rollout status deploy/nats -n agentforge-staging --timeout=120s
          kubectl rollout status deploy/temporalite -n agentforge-staging --timeout=120s
          kubectl rollout status deploy/nats-worker -n agentforge-staging --timeout=180s || true
          kubectl rollout status deploy/temporal-worker -n agentforge-staging --timeout=180s || true
          kubectl rollout status deploy/comms-gateway -n agentforge-staging --timeout=180s || true
      - name: Disable mTLS for comms-gateway tests
        run: |
          kubectl -n agentforge-staging set env deploy/comms-gateway COMMS_REQUIRE_MTLS=0
          kubectl -n agentforge-staging rollout status deploy/comms-gateway --timeout=180s || true
      - name: Seed JetStream and smoke publish
        run: |
          python -m pip install nats-py
          python scripts/nats_setup.py
          python scripts/smoke_publish.py
      - name: Check worker logs
        run: |
          kubectl logs deploy/nats-worker -n agentforge-staging --tail=200 || true
          kubectl logs deploy/temporal-worker -n agentforge-staging --tail=200 || true
      - name: Run comms gateway tests (via port-forward)
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          pip install pytest httpx websockets
          kubectl -n agentforge-staging port-forward svc/comms-gateway 18081:8081 >/dev/null 2>&1 &
          sleep 2
          COMMS_BASE=http://127.0.0.1:18081 COMMS_WS=ws://127.0.0.1:18081/ws pytest -q tests/test_comms_delivery_latency.py tests/test_comms_ratelimit.py || true
      - name: Run chaos suite and collect artifacts
        env:
          CHAOS: "1"
        run: |
          bash scripts/e2e/scale-from-zero.sh || true
          # Latest run directory
          TS=$(ls -1dt var/artifacts/chaos/*/ | head -n1 | xargs -n1 basename)
          RUN_DIR="var/artifacts/chaos/${TS}"
          echo "Artifacts at: $RUN_DIR"
          ls -la "$RUN_DIR" || true
      - name: Upload chaos artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: chaos-artifacts
          path: var/artifacts/chaos/**

  tactical-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 9

      - name: Install dependencies
        working-directory: ui/tactical-dashboard
        run: pnpm install --frozen-lockfile=false

      - name: Approve Puppeteer build and rebuild
        working-directory: ui/tactical-dashboard
        run: |
          pnpm approve-builds puppeteer || true
          pnpm rebuild puppeteer || true

      - name: npm audit (high)
        working-directory: ui/tactical-dashboard
        run: pnpm audit --audit-level=high || true

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087

      - name: Trivy FS scan
        working-directory: ui/tactical-dashboard
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Build
        working-directory: ui/tactical-dashboard
        run: pnpm build

      - name: Preview and snapshot
        working-directory: ui/tactical-dashboard
        env:
          PORT: 5173
        run: pnpm snapshot

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: tactical-dashboard-snapshots
          path: ui/tactical-dashboard/snapshots/*.png

      - name: Lighthouse CI
        working-directory: ui/tactical-dashboard
        run: npx lhci autorun --upload.target=temporary-public-storage || true

  comms-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087
      - name: Trivy FS scan (comms-gateway)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL services/comms_gateway || true
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'
      - name: Install Semgrep
        run: pip install semgrep
      - name: "Semgrep scan (rules: auto)"
        run: semgrep --error --config auto services/comms_gateway || true
