name: edge-verify

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: {}

jobs:
  edge-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio

      - name: Start NATS JetStream (docker)
        run: |
          docker rm -f nats-js-test >/dev/null 2>&1 || true
          docker run -d --name nats-js-test -p 4222:4222 -p 8222:8222 nats:2.10 -js

      - name: Wait for NATS to be ready
        run: |
          for i in $(seq 1 20); do
            nc -z localhost 4222 && break || sleep 0.5
          done

      - name: Run edge tests (store-forward + reconnect)
        env:
          NATS_URL: nats://localhost:4222
          EDGE_MODE: "1"
        run: |
          pytest -q tests/test_edge_store_forward.py tests/test_edge_disconnect_reconnect.py --junitxml=pytest-edge.xml

      - name: Run local backlog drain harness
        env:
          NATS_URL: nats://localhost:4222
        run: |
          python local_drain_test.py || true

      - name: Stop NATS
        if: always()
        run: docker rm -f nats-js-test || true

      - name: Upload edge verification artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-verify-${{ github.sha }}
          path: |
            pytest-edge.xml
            drain_test_results_*.json
          if-no-files-found: ignore
