name: kind-e2e-scale-from-zero

on:
  pull_request:
    paths:
      - 'k8s/staging/**'
      - 'swarm/**'
      - 'scripts/e2e/**'
      - '.github/workflows/kind-e2e-scale-from-zero.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up kind
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde
      - name: Build image
        run: docker build -t agentforge:ci .
      - name: Load image into kind
        run: kind load docker-image agentforge:ci
      - name: Deploy staging kustomize
        run: |
          kubectl apply -k k8s/staging
          kubectl -n agentforge-staging rollout status deploy/nats --timeout=120s
          kubectl -n agentforge-staging rollout status deploy/temporalite --timeout=120s
          kubectl -n agentforge-staging rollout status deploy/nats-worker --timeout=180s || true
          kubectl -n agentforge-staging rollout status deploy/temporal-worker --timeout=180s || true
      - name: Run scale-from-zero e2e
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          bash scripts/e2e/scale-from-zero.sh
      - name: Dump diagnostics on failure
        if: failure()
        run: |
          kubectl -n agentforge-staging get pods,deploy,hpa,scaledobject
          kubectl -n agentforge-staging describe scaledobject nats-worker-scaledobject || true
          kubectl -n agentforge-staging logs deploy/nats-worker --tail=200 || true
          kubectl -n agentforge-staging logs deploy/temporal-worker --tail=200 || true
